# Pipeline to force unlock TF state
# Required run time variables:
#
# lockId - the lock Id locking the state that is to be removed

trigger: none

pool: terraform

variables:
  environment: prod
  TF_IN_AUTOMATION: 1
  ARM_TENANT_ID: 
  keyvaultName: 

steps:
  - checkout: self

  - task: AzureKeyVault@1
    displayName: Download Secrets
    inputs:
      azureSubscription: 
      KeyVaultName: $(keyvaultName)
      SecretsFilter: 'azdevopspat,ARMCLIENTSECRET,ARMCLIENTID,ARMSUBSCRIPTIONID'
      RunAsPreJob: false

  - task: CmdLine@2
    displayName: Replace Tokens
    inputs:
      script: sed -i s/PATTOKEN1/$(azdevoptpat)/ *.tf

  - script: |
      terraform init -no-color -input=false -backend-config=backend-$(environment).hcl
    displayName: Terraform init
    env:
      ARM_CLIENT_ID: $(ARMCLIENTID)
      ARM_CLIENT_SECRET: $(ARMCLIENTSECRET)
      ARM_SUBSCRIPTION_ID: $(ARMSUBSCRIPTIONID)

  - script: |
      terraform force-unlock -force $LOCK_ID
    displayName: Terraform force unlock
    env:
      ARM_CLIENT_ID: $(ARMCLIENTID)
      ARM_CLIENT_SECRET: $(ARMCLIENTSECRET)
      ARM_SUBSCRIPTION_ID: $(ARMSUBSCRIPTIONID)
      LOCK_ID: $(lockId)
